settings:
  legacy:
    force: true
    interval: 10s
schema:
  - name: shin-kamishibaiZ
    path: ./cmd/server/
    commands:
      run:
        status: true
    # args:
    #   - -conf-dir
    #   - ~/etc/shin-kamishibai/test.conf
    watcher:
      extensions:
        - go
      paths:
        - ../../server
        - ../../pkg
      ignored_paths:
        - ../../.git
        - ../../.realize
        - ../../.history
        - ../../web
        - ../../vendor
